-- =====================================================================
-- qna_contact_message
-- 공개(비로그인) 문의하기 테이블 — 게스트 문의 + 관리자 수동 회신 기록(임베드)
-- 회원 1:1 문의(qna_inquiry)와 분리. 작성자 회원 계정 없이 회신용 이메일만 수집한다.
-- 설계 문서: docs/contact/contact-design.md
-- 대상 DB: PostgreSQL 17
-- 적용: prod 는 spring.jpa.hibernate.ddl-auto=none 이므로 이 DDL 을 수동 적용해야 한다.
-- =====================================================================

CREATE TABLE IF NOT EXISTS qna_contact_message (
    id             BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category       VARCHAR(20)  NOT NULL,
    title          VARCHAR(200) NOT NULL,
    content        TEXT         NOT NULL,
    guest_name     VARCHAR(100) NULL,
    guest_email    VARCHAR(255) NOT NULL,
    status         VARCHAR(20)  NOT NULL,
    reply_content  TEXT         NULL,
    replied_by_id  BIGINT       NULL,
    replied_at     TIMESTAMP(6) NULL,
    created_at     TIMESTAMP(6) NOT NULL,
    updated_at     TIMESTAMP(6) NOT NULL,
    CONSTRAINT fk_contact_replied_by FOREIGN KEY (replied_by_id) REFERENCES member (id) ON DELETE SET NULL
);

COMMENT ON TABLE  qna_contact_message               IS '공개(비로그인) 문의하기';
COMMENT ON COLUMN qna_contact_message.category      IS '문의 카테고리 (ACCOUNT/CONTENT/GAME/BUG/SUGGESTION/ETC)';
COMMENT ON COLUMN qna_contact_message.title         IS '문의 제목';
COMMENT ON COLUMN qna_contact_message.content       IS '문의 내용';
COMMENT ON COLUMN qna_contact_message.guest_name    IS '작성자 이름/호칭 (선택, NULL 허용)';
COMMENT ON COLUMN qna_contact_message.guest_email   IS '답변 회신용 이메일 (필수)';
COMMENT ON COLUMN qna_contact_message.status        IS '상태 (RECEIVED/REPLIED/CLOSED)';
COMMENT ON COLUMN qna_contact_message.reply_content IS '관리자 회신 본문 기록 (실제 발송은 수동/mailto, 회신 전 NULL)';
COMMENT ON COLUMN qna_contact_message.replied_by_id IS '회신 관리자 (member.id, 회신 전/회신자 탈퇴 후 NULL)';
COMMENT ON COLUMN qna_contact_message.replied_at    IS '회신 기록 시각 (회신 전 NULL)';

-- =====================================================================
-- 인덱스
-- =====================================================================

-- 관리자 목록 (상태별 최신순)
CREATE INDEX IF NOT EXISTS idx_contact_status_created_at
    ON qna_contact_message (status, created_at);
