server:
  forward-headers-strategy: framework

logging:
  config: classpath:logback-spring-local.xml

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    hikari:
      pool-name: ${spring.application.name}-${spring.profiles.active}-hikari-pool
      maximum-pool-size: 1
      minimum-idle: 1
      connection-timeout: 3000        # 3초
      validation-timeout: 1500        # 1.5초
      max-lifetime: 300000            # 5분 (PostgreSQL보다 짧게)
      leak-detection-threshold: 3000  # 3초
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show_sql: false
        format_sql: false
  cloud:
    gcp:
      credentials:
        location: classpath:keys/elseeker_gcp_project_key.json
      logging:
        enabled: false
      trace:
        enabled: false

management:
  tracing:
    enabled: false