server:
  port: 8080

spring:
  application:
    name: the_bible
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: true
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:test
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create
    open-in-view: false
    properties:
      hibernate:
        show_sql: false
        format_sql: false

springdoc:
  api-docs:
    groups:
      enabled: false
  swagger-ui:
    enabled: true
    groups-order: ASC
    tags-sorter: alpha
    operations-sorter: alpha
    display-request-duration: true
    doc-expansion: none
  cache:
    disabled: true
  model-and-view-allowed: true

api:
  the-bible:
    url: http://localhost:8080
    api-key: TEST_API_KEY