-- =====================================================================
-- 회원가입 동의 프로세스 개편 — prod 스키마 마이그레이션
-- 설계 문서: docs/policy/signup-consent-design.md
-- 대상 DB: PostgreSQL 17 (prod, ddl-auto: none)
-- 적용 시점: 신규 동의 흐름 배포 직전 1회 수동 실행
-- =====================================================================

-- ---------------------------------------------------------------------
-- 1) member.status 컬럼 추가 + 기존 회원 백필
--    기존 회원은 과거 간편 고지형 동의로 그랜드패더링 → ACTIVE.
--    신규 회원은 애플리케이션이 INSERT 시 PENDING_CONSENT 로 명시 지정.
-- ---------------------------------------------------------------------
ALTER TABLE member
    ADD COLUMN IF NOT EXISTS status VARCHAR(32) NOT NULL DEFAULT 'ACTIVE';

COMMENT ON COLUMN member.status IS '계정 상태: PENDING_CONSENT(동의 대기) / ACTIVE(정상)';

-- 백필 검증 후, 신규 행이 애플리케이션 값으로만 설정되도록 DEFAULT 제거(선택).
-- ALTER TABLE member ALTER COLUMN status DROP DEFAULT;

-- ---------------------------------------------------------------------
-- 2) member_consent_audit — 동의 이력 감사 테이블 (write-once)
--    가입 1회당 필수 항목 수만큼 행 생성: TERMS / PRIVACY / AGE_OVER_14
-- ---------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS member_consent_audit (
    id             BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    member_uid     UUID         NOT NULL,
    consent_type   VARCHAR(32)  NOT NULL,
    policy_version VARCHAR(32)  NOT NULL,
    agreed         BOOLEAN      NOT NULL,
    agreed_at      TIMESTAMP(6) NOT NULL,
    ip_address     VARCHAR(45)  NULL
);

COMMENT ON TABLE  member_consent_audit                IS '회원 약관/방침/연령 동의 이력 (write-once, 분쟁 증빙용)';
COMMENT ON COLUMN member_consent_audit.member_uid     IS '동의 주체 Member.uid (FK 제약 없음, 탈퇴 후에도 보존 가능)';
COMMENT ON COLUMN member_consent_audit.consent_type   IS 'TERMS / PRIVACY / AGE_OVER_14 (확장: MARKETING)';
COMMENT ON COLUMN member_consent_audit.policy_version IS '동의 시점 약관/방침 버전(최종 개정일 기준). AGE_OVER_14 는 N/A';
COMMENT ON COLUMN member_consent_audit.agreed         IS '동의 여부(필수 항목은 항상 true)';
COMMENT ON COLUMN member_consent_audit.agreed_at      IS '동의 시각 (UTC, Instant)';
COMMENT ON COLUMN member_consent_audit.ip_address     IS '동의 시점 접속 IP (IPv4/IPv6, 분쟁 증빙용)';

-- ---------------------------------------------------------------------
-- 인덱스
-- ---------------------------------------------------------------------
CREATE INDEX IF NOT EXISTS idx_member_consent_audit_member_uid
    ON member_consent_audit (member_uid);

CREATE INDEX IF NOT EXISTS idx_member_consent_audit_member_uid_type
    ON member_consent_audit (member_uid, consent_type);
