-- =====================================================================
-- app_install_banner_event
-- Android 앱 설치 유도 배너 이벤트 원시 저장 테이블
-- 설계 문서: docs/googleplay/app-install-banner-prd.md
-- 대상 DB: PostgreSQL 17
-- 완전 익명 집계 — member_uid 등 회원 식별 정보 컬럼 없음 (PRD 13장)
-- =====================================================================

CREATE TABLE IF NOT EXISTS app_install_banner_event (
    id            BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    visitor_id    VARCHAR(36)  NOT NULL,
    event_type    VARCHAR(20)  NOT NULL,
    is_bot        BOOLEAN      NOT NULL,
    occurred_at   TIMESTAMP(6) NOT NULL,
    occurred_date DATE         NOT NULL,
    created_at    TIMESTAMP(6) NOT NULL,
    updated_at    TIMESTAMP(6) NOT NULL
);

COMMENT ON TABLE  app_install_banner_event               IS 'Android 앱 설치 유도 배너 이벤트 원시 로그 (완전 익명)';
COMMENT ON COLUMN app_install_banner_event.visitor_id    IS '단방향 해시된 익명 방문자 식별자 (SHA-256, 원본 es_visitor_id 와 교차 식별 불가)';
COMMENT ON COLUMN app_install_banner_event.event_type    IS '이벤트 종류 (IMPRESSION | CLICK | DISMISS)';
COMMENT ON COLUMN app_install_banner_event.is_bot        IS '봇 User-Agent 판정 결과';
COMMENT ON COLUMN app_install_banner_event.occurred_at   IS '이벤트 발생 시각 (UTC, Instant)';
COMMENT ON COLUMN app_install_banner_event.occurred_date IS '집계 기준 날짜 (Asia/Seoul)';

-- =====================================================================
-- 인덱스
-- 단일 occurred_date 조회는 복합 인덱스의 좌측 프리픽스로 충족됨
-- =====================================================================

CREATE INDEX IF NOT EXISTS idx_app_install_banner_event_occurred_date_event_type
    ON app_install_banner_event (occurred_date, event_type);
