-- =====================================================================
-- apple_notification_audit
-- Apple 서버-대-서버 알림(Sign in with Apple) 수신 이력
-- 매핑 엔티티: com.elseeker.auth.domain.model.AppleNotificationAudit
-- 수신 엔드포인트: POST /api/v1/auth/apple/notifications (AppleNotificationApi)
-- 대상 DB: PostgreSQL 17
-- =====================================================================
--
-- 남기는 이유
--  1. 중복 수신 차단 — Apple 은 같은 알림을 재전송한다. (jti, event_type, apple_sub) 로 걸러낸다.
--  2. 근거 보존 — 회원이 하드 삭제된 뒤 "왜 지웠는가"에 답할 수 있는 유일한 기록이다.
--
-- member_uid 에 FK 를 걸지 않는 이유: 회원은 탈퇴 시 하드 삭제되므로 FK 가 있으면 이력이 함께
-- 사라지거나 삭제 자체가 막힌다. 삭제 후에도 근거가 남아야 한다.

CREATE TABLE IF NOT EXISTS apple_notification_audit (
    id               BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    jti              VARCHAR(255) NOT NULL,
    event_type       VARCHAR(64)  NOT NULL,
    apple_sub        VARCHAR(255) NOT NULL,
    email            VARCHAR(255) NULL,
    is_private_email BOOLEAN      NULL,
    occurred_at      TIMESTAMP(6) NULL,
    result           VARCHAR(32)  NOT NULL,
    member_uid       UUID         NULL,
    created_at       TIMESTAMP(6) NOT NULL,
    updated_at       TIMESTAMP(6) NOT NULL
);

COMMENT ON TABLE  apple_notification_audit                  IS 'Apple 서버-대-서버 알림 수신 이력';
COMMENT ON COLUMN apple_notification_audit.jti              IS '알림 토큰 식별자. Apple 재전송 시 값이 같아 중복 판별에 사용';
COMMENT ON COLUMN apple_notification_audit.event_type       IS 'Apple 이 보낸 원본 타입 문자열. 미지원 타입도 그대로 보관';
COMMENT ON COLUMN apple_notification_audit.apple_sub        IS 'Apple 사용자 식별자(sub). member_oauth_account.provider_user_id 와 대응';
COMMENT ON COLUMN apple_notification_audit.email            IS '이메일 관련 이벤트에서 Apple 이 내려준 주소 (비공개 릴레이일 수 있음)';
COMMENT ON COLUMN apple_notification_audit.is_private_email IS 'Apple 비공개 이메일 릴레이 주소 여부';
COMMENT ON COLUMN apple_notification_audit.occurred_at      IS 'Apple 이 알려 준 이벤트 발생 시각 (UTC). 수신 시각은 created_at';
COMMENT ON COLUMN apple_notification_audit.result           IS '처리 결과 (MEMBER_WITHDRAWN / MEMBER_NOT_FOUND / NO_ACTION / UNSUPPORTED_TYPE)';
COMMENT ON COLUMN apple_notification_audit.member_uid       IS '처리 대상 회원의 uid. 대상이 없었으면 NULL (FK 제약 없음)';

-- =====================================================================
-- 제약
-- =====================================================================

-- 재전송 멱등성의 최후 방어선. 한 토큰(jti)에 여러 이벤트가 담길 수 있어 jti 단독으로는 유일하지 않다.
ALTER TABLE apple_notification_audit
    DROP CONSTRAINT IF EXISTS uk_apple_notification_audit_event;
ALTER TABLE apple_notification_audit
    ADD CONSTRAINT uk_apple_notification_audit_event UNIQUE (jti, event_type, apple_sub);

-- =====================================================================
-- 인덱스
-- =====================================================================

CREATE INDEX IF NOT EXISTS idx_apple_notification_audit_apple_sub
    ON apple_notification_audit (apple_sub);
