-- =====================================================================
-- bible_word_stat
-- 성경 책/장 단위 단어 언급 횟수 테이블
-- 설계 문서: docs/bible/word-frequency-design.md
-- 대상 DB: PostgreSQL 17
-- =====================================================================
--
-- 주의: 행 수가 번역본당 약 15만 규모로 커진다(설계 문서 §5.5).
--       created_at / updated_at 을 일부러 두지 않는다. 재계산 시각은
--       bible_word_stat_run 에 책 단위로 기록한다.

CREATE TABLE IF NOT EXISTS bible_word_stat (
    id             BIGINT      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    bible_word_id  BIGINT      NOT NULL,
    translation_id BIGINT      NOT NULL,
    book_order     INT         NOT NULL,
    chapter_number INT         NOT NULL,
    word_count     INT         NOT NULL,
    source         VARCHAR(10) NOT NULL,
    CONSTRAINT uk_bible_word_stat
        UNIQUE (translation_id, book_order, chapter_number, bible_word_id)
);

CREATE INDEX IF NOT EXISTS idx_bible_word_stat_scope
    ON bible_word_stat (translation_id, book_order, chapter_number, word_count DESC);

CREATE INDEX IF NOT EXISTS idx_bible_word_stat_word
    ON bible_word_stat (bible_word_id);

COMMENT ON TABLE  bible_word_stat                IS '성경 책/장 단위 단어 언급 횟수';
COMMENT ON COLUMN bible_word_stat.chapter_number IS '장 번호. 0 이면 책 전체 집계 (상위 300개만 저장)';
COMMENT ON COLUMN bible_word_stat.word_count     IS '언급 횟수. 0 인 행은 저장하지 않는다';
COMMENT ON COLUMN bible_word_stat.source         IS 'AUTO=자동 계산(재계산 시 삭제 후 재삽입), MANUAL=관리자 입력(재계산 시 보존)';
