-- =====================================================================
-- bible_word_alias
-- 표제어 별칭·이형태 테이블
-- 설계 문서: docs/bible/word-frequency-design.md
-- 대상 DB: PostgreSQL 17
-- =====================================================================

CREATE TABLE IF NOT EXISTS bible_word_alias (
    id             BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    bible_word_id  BIGINT       NOT NULL,
    translation_id BIGINT       NOT NULL,
    alias          VARCHAR(50)  NOT NULL,
    created_at     TIMESTAMP(6) NOT NULL,
    updated_at     TIMESTAMP(6) NOT NULL,
    CONSTRAINT uk_bible_word_alias UNIQUE (translation_id, alias)
);

CREATE INDEX IF NOT EXISTS idx_bible_word_alias_word
    ON bible_word_alias (bible_word_id);

COMMENT ON TABLE  bible_word_alias                IS '표제어 별칭·이형태 (같은 번역본 안에서 유일해야 함)';
COMMENT ON COLUMN bible_word_alias.translation_id IS '부모 bible_word.translation_id 와 동일해야 함. 유니크 제약을 번역본 단위로 걸기 위해 복제';
COMMENT ON COLUMN bible_word_alias.alias          IS '표기 자체가 다른 경우만 등록. 조사 결합형(땅에/땅을)은 등록 금지 — 정규화 규칙에서 처리';
