-- =====================================================================
-- bible_word
-- 성경 단어 빈도 통계 표제어 어휘 테이블
-- 설계 문서: docs/bible/word-frequency-design.md
-- 대상 DB: PostgreSQL 17
-- =====================================================================

CREATE TABLE IF NOT EXISTS bible_word (
    id             BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    translation_id BIGINT       NOT NULL,
    term           VARCHAR(50)  NOT NULL,
    category       VARCHAR(20)  NOT NULL,
    status         VARCHAR(20)  NOT NULL,
    dictionary_id  BIGINT       NULL,
    note           TEXT         NULL,
    created_at     TIMESTAMP(6) NOT NULL,
    updated_at     TIMESTAMP(6) NOT NULL,
    CONSTRAINT uk_bible_word_term UNIQUE (translation_id, term)
);

CREATE INDEX IF NOT EXISTS idx_bible_word_status
    ON bible_word (translation_id, status);

COMMENT ON TABLE  bible_word                IS '성경 단어 빈도 통계 표제어 어휘';
COMMENT ON COLUMN bible_word.translation_id IS '어휘는 번역본별로 관리한다. 언어는 bible_translation.language_code 에서 끌어온다';
COMMENT ON COLUMN bible_word.term           IS '표제어';
COMMENT ON COLUMN bible_word.category       IS 'PERSON/PLACE/CONCEPT/OBJECT/MEASURE/ETC. 자동 추출 후보는 ETC';
COMMENT ON COLUMN bible_word.status         IS 'APPROVED=노출, CANDIDATE=미검수, BLOCKED=영구 제외';
COMMENT ON COLUMN bible_word.dictionary_id  IS '성경 사전(dictionary) 연결. NULL 이면 뜻풀이 없음. FK 제약은 걸지 않는다';
COMMENT ON COLUMN bible_word.note           IS '관리자 메모(조사 출처 등). 사용자에게 노출하지 않음';
