-- =====================================================================
-- bible_word_stat_run
-- 단어 통계 재계산 이력 테이블 (번역본 x 책 단위 1행)
-- 설계 문서: docs/bible/word-frequency-design.md
-- 대상 DB: PostgreSQL 17
-- =====================================================================

CREATE TABLE IF NOT EXISTS bible_word_stat_run (
    id             BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    translation_id BIGINT       NOT NULL,
    book_order     INT          NOT NULL,
    calculated_at  TIMESTAMP(6) NOT NULL,
    chapter_count  INT          NOT NULL,
    stat_row_count INT          NOT NULL,
    manual_kept    INT          NOT NULL,
    created_at     TIMESTAMP(6) NOT NULL,
    updated_at     TIMESTAMP(6) NOT NULL,
    CONSTRAINT uk_bible_word_stat_run UNIQUE (translation_id, book_order)
);

COMMENT ON TABLE  bible_word_stat_run                IS '단어 통계 재계산 이력 (번역본 x 책 단위 1행)';
COMMENT ON COLUMN bible_word_stat_run.calculated_at  IS '마지막 재계산 시각 (UTC). 사용자 응답의 calculatedAt 출처';
COMMENT ON COLUMN bible_word_stat_run.chapter_count  IS '처리한 장 수';
COMMENT ON COLUMN bible_word_stat_run.stat_row_count IS '기록한 통계 행 수 (장 행 + 책 행)';
COMMENT ON COLUMN bible_word_stat_run.manual_kept    IS '재계산 시 보존한 MANUAL 행 수';
