-- =====================================================================
-- dictionary_search_keyword
-- 성경 사전 검색 키워드 누적 집계 테이블
-- 설계 문서: docs/study/dictionary-search-keyword-ranking-design.md
-- 대상 DB: PostgreSQL 17
-- =====================================================================

CREATE TABLE IF NOT EXISTS dictionary_search_keyword (
    id                  BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    normalized_keyword  VARCHAR(50)  NOT NULL,
    keyword             VARCHAR(50)  NOT NULL,
    search_count        BIGINT       NOT NULL DEFAULT 0,
    blocked             BOOLEAN      NOT NULL DEFAULT false,
    last_searched_at    TIMESTAMP(6) NOT NULL,
    created_at          TIMESTAMP(6) NOT NULL,
    updated_at          TIMESTAMP(6) NOT NULL,
    CONSTRAINT uk_dictionary_search_keyword_normalized UNIQUE (normalized_keyword)
);

COMMENT ON TABLE  dictionary_search_keyword                    IS '성경 사전 검색 키워드 누적 집계';
COMMENT ON COLUMN dictionary_search_keyword.normalized_keyword IS '정규화 키워드 (집계 키, 유니크)';
COMMENT ON COLUMN dictionary_search_keyword.keyword            IS '최근 검색 원본 키워드';
COMMENT ON COLUMN dictionary_search_keyword.search_count       IS '누적 검색 횟수';
COMMENT ON COLUMN dictionary_search_keyword.blocked            IS '공개 랭킹 노출 제외 여부';
COMMENT ON COLUMN dictionary_search_keyword.last_searched_at   IS '최근 검색 시각 (UTC)';

-- =====================================================================
-- 인덱스
-- =====================================================================

CREATE INDEX IF NOT EXISTS idx_dictionary_search_keyword_count_desc
    ON dictionary_search_keyword (blocked, search_count DESC, last_searched_at DESC);

CREATE INDEX IF NOT EXISTS idx_dictionary_search_keyword_last_searched_at
    ON dictionary_search_keyword (last_searched_at DESC);
