-- =====================================================================
-- qna_inquiry
-- 1:1 문의(질의응답) 테이블 — 회원 질문 + 관리자 단일 답변(임베드)
-- 설계 문서: docs/qna/qna-design.md
-- 대상 DB: PostgreSQL 17
-- =====================================================================

CREATE TABLE IF NOT EXISTS qna_inquiry (
    id              BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    author_id       BIGINT       NOT NULL,
    category        VARCHAR(20)  NOT NULL,
    title           VARCHAR(200) NOT NULL,
    content         TEXT         NOT NULL,
    status          VARCHAR(20)  NOT NULL,
    answer_content  TEXT         NULL,
    answered_by_id  BIGINT       NULL,
    answered_at     TIMESTAMP(6) NULL,
    created_at      TIMESTAMP(6) NOT NULL,
    updated_at      TIMESTAMP(6) NOT NULL,
    CONSTRAINT fk_inquiry_author      FOREIGN KEY (author_id)      REFERENCES member (id),
    CONSTRAINT fk_inquiry_answered_by FOREIGN KEY (answered_by_id) REFERENCES member (id) ON DELETE SET NULL
);

COMMENT ON TABLE  qna_inquiry                 IS '1:1 문의(질의응답)';
COMMENT ON COLUMN qna_inquiry.author_id       IS '문의 작성 회원 (member.id)';
COMMENT ON COLUMN qna_inquiry.category        IS '문의 카테고리 (ACCOUNT/CONTENT/GAME/BUG/SUGGESTION/ETC)';
COMMENT ON COLUMN qna_inquiry.status          IS '상태 (RECEIVED/ANSWERED/CLOSED/DELETED)';
COMMENT ON COLUMN qna_inquiry.answer_content  IS '관리자 답변 본문 (답변 전 NULL)';
COMMENT ON COLUMN qna_inquiry.answered_by_id  IS '답변 관리자 (member.id, 답변 전/답변자 탈퇴 후 NULL)';
COMMENT ON COLUMN qna_inquiry.answered_at     IS '답변 시각 (답변 전 NULL)';

-- =====================================================================
-- 인덱스
-- =====================================================================

-- 내 문의 목록 (작성자별 최신순)
CREATE INDEX IF NOT EXISTS idx_inquiry_author_created_at
    ON qna_inquiry (author_id, created_at);

-- 관리자 목록 (상태별 최신순)
CREATE INDEX IF NOT EXISTS idx_inquiry_status_created_at
    ON qna_inquiry (status, created_at);
