-- =====================================================================
-- site_visit_event
-- 사이트 방문 이벤트 원시 저장 테이블
-- 설계 문서: docs/common/site-visitor-count-design.md
-- 대상 DB: PostgreSQL 17
-- =====================================================================

CREATE TABLE IF NOT EXISTS site_visit_event (
                                                id               BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                                visitor_id       VARCHAR(36)  NOT NULL,
    member_uid       UUID         NULL,
    page_key         VARCHAR(160) NOT NULL,
    request_uri      VARCHAR(255) NOT NULL,
    referer_host     VARCHAR(120) NULL,
    is_authenticated BOOLEAN      NOT NULL,
    is_bot           BOOLEAN      NOT NULL,
    visited_at       TIMESTAMP(6) NOT NULL,
    visited_date     DATE         NOT NULL,
    created_at       TIMESTAMP(6) NOT NULL,
    updated_at       TIMESTAMP(6) NOT NULL
    );

COMMENT ON TABLE  site_visit_event                    IS '사이트 방문 이벤트 원시 로그';
COMMENT ON COLUMN site_visit_event.visitor_id         IS '쿠키 기반 방문자 식별자 (UUID 문자열)';
COMMENT ON COLUMN site_visit_event.member_uid         IS '로그인 사용자의 JwtPrincipal.memberUid, 비회원은 NULL (FK 제약 없음)';
COMMENT ON COLUMN site_visit_event.page_key           IS 'HandlerMapping.BEST_MATCHING_PATTERN_ATTRIBUTE 기반 정규화 경로';
COMMENT ON COLUMN site_visit_event.request_uri        IS '실제 요청 URI (쿼리스트링 제외)';
COMMENT ON COLUMN site_visit_event.referer_host       IS 'Referer 헤더에서 추출한 host';
COMMENT ON COLUMN site_visit_event.is_authenticated   IS '로그인 상태 여부';
COMMENT ON COLUMN site_visit_event.is_bot             IS '봇 User-Agent 판정 결과';
COMMENT ON COLUMN site_visit_event.visited_at         IS '방문 시각 (UTC, Instant)';
COMMENT ON COLUMN site_visit_event.visited_date       IS '집계 기준 날짜 (Asia/Seoul)';

-- =====================================================================
-- 인덱스
-- =====================================================================

CREATE INDEX IF NOT EXISTS idx_site_visit_event_visited_date
    ON site_visit_event (visited_date);

CREATE INDEX IF NOT EXISTS idx_site_visit_event_visited_date_page_key
    ON site_visit_event (visited_date, page_key);

CREATE INDEX IF NOT EXISTS idx_site_visit_event_visited_date_visitor_id
    ON site_visit_event (visited_date, visitor_id);

CREATE INDEX IF NOT EXISTS idx_site_visit_event_member_uid_visited_date
    ON site_visit_event (member_uid, visited_date);
