INSERT INTO bible_book_description (book_key, language_code, summary, author, written_year, historical_period, background, content)
VALUES ('GEN', 'en',
        'Genesis records the creation of the world and the beginnings of mankind and Israel.',
        'Moses',
        'c. 1445–1405 BC',
        'Creation to Patriarchal Era',
        'Genesis covers the origin of the universe, humanity, sin, and God''s covenant with Abraham''s family, ending with Joseph in Egypt.',
        'Genesis introduces God as the Creator and establishes the foundation for all Scripture. It recounts the stories of Adam and Eve, Noah, Abraham, Isaac, Jacob, and Joseph, showing God''s covenant and providence.'),
       ('EXO', 'en',
        'Exodus tells of Israel''s deliverance from Egypt and the giving of the Law.',
        'Moses',
        'c. 1445–1405 BC',
        'Exodus and Wilderness Era',
        'Describes God''s deliverance of Israel from Egypt through Moses and the giving of the Law at Sinai.',
        'Exodus details God''s deliverance of Israel through Moses, the plagues, the parting of the Red Sea, the Ten Commandments, and the instructions for building the Tabernacle.'),
       ('LEV', 'en',
        'Leviticus outlines laws for worship and holiness for the people of Israel.',
        'Moses',
        'c. 1445–1405 BC',
        'Wilderness at Mount Sinai',
        'Focuses on laws concerning worship, sacrifice, and purity given at Mount Sinai.',
        'Leviticus emphasizes holiness, sacrificial systems, and regulations for priests and people, providing a blueprint for living in covenant with a holy God.'),
       ('NUM', 'en',
        'Numbers recounts Israel''s journey through the wilderness.',
        'Moses',
        'c. 1445–1405 BC',
        'Wilderness Wandering',
        'Documents Israel''s travels, census, and complaints during the journey from Sinai to the Promised Land.',
        'Numbers covers Israel''s wanderings, census counts, and rebellions, highlighting God''s faithfulness despite the people''s frequent disobedience.'),
       ('DEU', 'en',
        'Deuteronomy is Moses'' farewell speech, summarizing the Law before entering Canaan.',
        'Moses',
        'c. 1405 BC',
        'End of Wilderness Era',
        'Restates the Law for a new generation and urges covenant loyalty before entering the Promised Land.',
        'Deuteronomy restates the Law to a new generation of Israelites, urging covenant loyalty and preparing them to enter the Promised Land.'),
       ('JOS', 'en',
        'Joshua describes the conquest and division of the Promised Land.',
        'Joshua',
        'c. 1400–1370 BC',
        'Conquest of Canaan',
        'Joshua leads Israel into Canaan, conquering cities and allotting tribal inheritance.',
        'Joshua chronicles Israel''s victories under God''s leadership, dividing the land among the tribes and calling for covenant faithfulness.'),
       ('JDG', 'en',
        'Judges covers the cycles of sin, judgment, and deliverance in Israel''s early history.',
        'Samuel (traditionally attributed)',
        'c. 1050 BC',
        'Period of the Judges',
        'Israel repeatedly turns from God, suffers oppression, and is delivered by appointed judges.',
        'Judges presents a repeated pattern of sin, oppression, repentance, and deliverance, showing Israel''s need for godly leadership and God''s mercy.'),
       ('RUT', 'en',
        'Ruth tells a story of loyalty, redemption, and the lineage of David.',
        'Samuel (traditionally attributed)',
        'c. 1000 BC',
        'Judges Era',
        'A Moabite woman''s loyalty to her Hebrew mother-in-law leads to her place in David''s genealogy.',
        'Ruth is a story of faithfulness, kindness, and divine providence, showing how a Moabite woman became the great-grandmother of King David.'),
       ('FIRST_SAMUEL', 'en', '1 Samuel introduces the prophet Samuel, King Saul, and young David.', 'Samuel', 'c. 1050–1010 BC', 'United Monarchy',
        'Describes the transition from judges to kings with the rise and fall of Saul and the anointing of David.',
        '1 Samuel traces the transition from the era of judges to monarchy, detailing the rise and fall of Saul and the anointing of David.'),
       ('SECOND_SAMUEL', 'en', '2 Samuel focuses on the reign of King David over Israel.', 'Samuel, Nathan, Gad', 'c. 1010–970 BC', 'Reign of David',
        'Narrates David''s victories, sins, and the covenant God made with him.',
        '2 Samuel records David''s rule, triumphs, sins, and God''s covenant with him, foreshadowing the coming Messiah.'),
       ('FIRST_KINGS', 'en', '1 Kings recounts Solomon''s reign and the division of the kingdom.', 'Jeremiah (traditionally attributed)', 'c. 560 BC',
        'Divided Kingdom Begins', 'Starts with Solomon and ends with Elijah''s ministry and the decline of the kingdom.',
        '1 Kings begins with Solomon''s wisdom and temple construction, but later shows national decline and division into northern and southern kingdoms.'),
       ('SECOND_KINGS', 'en', '2 Kings continues the history of both kingdoms until their captivity.', 'Jeremiah (traditionally attributed)', 'c. 560 BC',
        'Fall of Israel and Judah', 'Describes the downfall of Israel and Judah due to idolatry and disobedience.',
        '2 Kings depicts the moral decay of Israel and Judah, leading to their respective falls to Assyria and Babylon.'),
       ('FIRST_CHRONICLES', 'en', '1 Chronicles retells Israel''s history with focus on David and temple worship.', 'Ezra (traditionally attributed)', 'c. 450 BC',
        'Post-Exilic Perspective', 'Highlights genealogies and temple preparation under David''s leadership.',
        '1 Chronicles emphasizes David''s lineage, military achievements, and preparations for building the temple, highlighting proper worship.'),
       ('SECOND_CHRONICLES', 'en', '2 Chronicles emphasizes the kings of Judah and the temple.', 'Ezra (traditionally attributed)', 'c. 450 BC',
        'Post-Exilic Perspective',
        'Focuses on temple worship and southern kingdom (Judah) kings.',
        '2 Chronicles continues with Solomon''s reign and the kings of Judah, focusing on obedience, temple worship, and God''s faithfulness.'),
       ('EZR', 'en', 'Ezra narrates the return from exile and the rebuilding of the temple.', 'Ezra', 'c. 440 BC', 'Return from Exile',
        'Describes the return from Babylonian captivity and temple reconstruction.',
        'Ezra describes the return of Jewish exiles from Babylon and the spiritual and religious reforms that followed, especially temple restoration.'),
       ('NEH', 'en', 'Nehemiah tells of the rebuilding of Jerusalem''s walls and reform.', 'Nehemiah', 'c. 430 BC', 'Return from Exile',
        'Details wall rebuilding, spiritual renewal, and Nehemiah''s leadership.',
        'Nehemiah focuses on reconstructing Jerusalem''s walls and restoring the people''s covenant commitment through reforms and prayer.'),
       ('EST', 'en', 'Esther tells of a Jewish queen who saved her people from destruction.', 'Mordecai (traditionally attributed)', 'c. 470 BC',
        'Persian Empire Era', 'Demonstrates God''s providence through Esther despite His name not being mentioned.',
        'Esther illustrates God''s providence in delivering the Jews through Queen Esther''s courage, despite His name not being explicitly mentioned.'),
       ('JOB', 'en', 'Job explores suffering, righteousness, and God''s justice.', 'Moses (traditionally attributed)', 'c. 2000–1000 BC',
        'Patriarchal Period',
        'Examines why the righteous suffer through dialogues between Job and his friends.',
        'Job wrestles with profound questions of suffering and divine justice, ultimately affirming God''s sovereignty and the value of faith in trials.'),
       ('PSA', 'en', 'Psalms is a collection of songs and prayers expressing worship and trust in God.', 'David and others', 'c. 1000–400 BC',
        'Monarchy to Post-Exile', 'Reflects the spiritual heart of Israel with diverse expressions of faith.',
        'Psalms captures the full range of human emotion in worship—praise, lament, thanksgiving, and confession—directed toward a faithful God.'),
       ('PRO', 'en', 'Proverbs offers practical wisdom for godly living.', 'Solomon and others', 'c. 950–700 BC', 'United Monarchy',
        'Compilation of wise sayings about relationships, work, and speech.',
        'Proverbs provides timeless wisdom for daily life, urging readers to fear the Lord and live righteously and wisely.'),
       ('ECC', 'en', 'Ecclesiastes reflects on the meaning and vanity of life under the sun.', 'Solomon', 'c. 935 BC', 'Late United Monarchy',
        'Philosophical reflections on life''s meaning apart from God.',
        'Ecclesiastes questions the meaning of life and concludes that revering God and keeping His commandments is the true purpose.'),
       ('SNG', 'en', 'Song of Solomon is a poetic celebration of love and marriage.', 'Solomon', 'c. 950 BC', 'United Monarchy',
        'A love poem expressing romantic desire and covenantal love.',
        'Song of Solomon celebrates romantic love within marriage, often interpreted symbolically as God''s love for His people.'),
       ('ISA', 'en', 'Isaiah prophesies judgment and redemption, highlighting the coming Messiah.', 'Isaiah', 'c. 740–681 BC', 'Pre-Exilic Judah',
        'Contains messianic prophecies, calls to repentance, and visions of hope.',
        'Isaiah blends warnings of judgment with promises of hope and redemption, including detailed messianic prophecies.'),
       ('JER', 'en', 'Jeremiah calls for repentance and warns of impending judgment.', 'Jeremiah', 'c. 627–586 BC', 'Last Days of Judah',
        'Preaches repentance before Babylonian exile and laments Israel''s sin.',
        'Jeremiah urges Judah to repent before Babylon''s invasion, expressing both divine sorrow and hope for a new covenant.'),
       ('LAM', 'en', 'Lamentations mourns the fall of Jerusalem.', 'Jeremiah', 'c. 586 BC', 'After Fall of Jerusalem',
        'Series of laments expressing grief over Jerusalem''s destruction.',
        'Lamentations expresses grief over Jerusalem''s destruction and affirms God''s mercy amidst sorrow.'),
       ('EZK', 'en', 'Ezekiel gives vivid visions of judgment and future restoration.', 'Ezekiel', 'c. 593–571 BC', 'Babylonian Exile',
        'Visions, allegories, and symbolic acts proclaim God''s glory and future restoration.',
        'Ezekiel includes symbolic acts and visions, portraying God''s justice and the future hope of restoration and a new temple.'),
       ('DAN', 'en', 'Daniel includes stories of faith and apocalyptic visions of future kingdoms.', 'Daniel', 'c. 605–530 BC',
        'Babylonian & Persian Rule',
        'Includes prophetic visions and faithful witness under foreign kings.',
        'Daniel displays courage under pagan rule and prophesies about God''s everlasting kingdom through dreams and visions.'),
       ('HOS', 'en', 'Hosea portrays God''s steadfast love despite Israel''s unfaithfulness.', 'Hosea', 'c. 750 BC', 'Northern Kingdom Before Fall',
        'Uses Hosea''s marriage as a metaphor for God and Israel.',
        'Hosea''s marriage illustrates God''s love for His wayward people and His desire for their return.'),
       ('JOL', 'en', 'Joel warns of the Day of the Lord and promises restoration.', 'Joel', 'c. 835 BC', 'Early Kingdom of Judah',
        'Describes locust plague and calls for national repentance.',
        'Joel describes locust plagues as a picture of judgment, calling for repentance and foretelling the outpouring of the Spirit.'),
       ('AMO', 'en', 'Amos calls for justice and warns of judgment on Israel.', 'Amos', 'c. 760 BC', 'Northern Kingdom Prosperity',
        'Rebukes religious hypocrisy and social injustice.',
        'Amos rebukes Israel''s social injustice and religious hypocrisy, calling the people to seek God and live.'),
       ('OBA', 'en', 'Obadiah foretells the downfall of Edom for its pride.', 'Obadiah', 'c. 845 BC', 'Judah under Attack',
        'Condemns Edom''s violence and arrogance.', 'Obadiah declares God''s judgment against Edom and affirms Zion''s future deliverance.'),
       ('JON', 'en', 'Jonah tells of the reluctant prophet and Nineveh''s repentance.', 'Jonah', 'c. 760 BC', 'During Assyrian Threat',
        'God sends Jonah to call Nineveh to repentance.',
        'Jonah runs from God''s call but ultimately delivers a message of repentance to Nineveh, revealing God''s compassion.'),
       ('MIC', 'en', 'Micah announces judgment and the future reign of the Messiah.', 'Micah', 'c. 735–700 BC', 'Divided Kingdom',
        'Judgment against injustice and hope of restoration.',
        'Micah foretells judgment and restoration, including the prophecy of the Messiah''s birth in Bethlehem.'),
       ('NAM', 'en', 'Nahum predicts Nineveh''s fall due to its wickedness.', 'Nahum', 'c. 660 BC', 'Fall of Assyria',
        'Declares God''s vengeance on Assyria.', 'Nahum proclaims the downfall of the Assyrian empire, revealing God''s justice against oppressors.'),
       ('HAB', 'en', 'Habakkuk questions God''s justice and learns to trust Him.', 'Habakkuk', 'c. 612 BC', 'Impending Babylonian Invasion',
        'Dialogues with God over the success of the wicked.',
        'Habakkuk dialogues with God over injustice and concludes with a declaration of faith in God''s sovereignty.'),
       ('ZEP', 'en', 'Zephaniah warns of coming judgment and urges humility.', 'Zephaniah', 'c. 640 BC', 'Josiah''s Reign',
        'Proclaims the Day of the Lord and promises restoration.',
        'Zephaniah warns of the Day of the Lord and encourages the faithful to seek the Lord for protection and hope.'),
       ('HAG', 'en', 'Haggai urges the people to rebuild the temple.', 'Haggai', 'c. 520 BC', 'Return from Exile',
        'Calls exiles to prioritize rebuilding God''s house.',
        'Haggai calls the returned exiles to prioritize rebuilding the temple, promising that God''s glory will fill it.'),
       ('ZEC', 'en', 'Zechariah encourages the returnees and prophesies of the Messiah.', 'Zechariah', 'c. 520–480 BC', 'Return from Exile',
        'Offers encouragement and messianic visions.',
        'Zechariah delivers visions of encouragement, spiritual renewal, and messianic hope to the post-exilic community.'),
       ('MAL', 'en', 'Malachi rebukes spiritual apathy and foretells a coming messenger.', 'Malachi', 'c. 430 BC', 'Post-Exilic Period',
        'Rebukes Israel''s religious apathy and anticipates a new Elijah.',
        'Malachi warns of religious indifference and anticipates the coming of Elijah to prepare the way for the Lord.');

INSERT INTO bible_book_description (book_key, language_code, summary, author, written_year, historical_period, background, content)
VALUES ('MAT', 'en', 'Matthew presents Jesus as the promised Messiah and King of the Jews.',
        'Matthew', 'c. AD 50–60', 'Life of Jesus', 'Written to Jewish audience to demonstrate Jesus as the fulfillment of Old Testament prophecies.',
        'Matthew highlights Jesus'' fulfillment of Old Testament prophecies, presenting Him as the rightful King and Messiah. It includes the Sermon on the Mount, parables, and the Great Commission.'),
       ('MRK', 'en', 'Mark highlights Jesus'' actions and authority as the Son of God.',
        'Mark', 'c. AD 50–60', 'Life of Jesus', 'Emphasizes Jesus'' miracles and servant nature with fast-paced narrative.',
        'Mark is the shortest Gospel, focusing on Jesus'' miracles, authority, and servant leadership. It emphasizes urgency and discipleship through fast-paced narrative.'),
       ('LUK', 'en', 'Luke provides a detailed account of Jesus'' life, emphasizing compassion and salvation.',
        'Luke', 'c. AD 60–62', 'Life of Jesus',
        'Luke, a physician and historian, wrote an orderly account to Theophilus, focusing on Jesus'' compassion and universal salvation.',
        'Luke, a physician and historian, emphasizes Jesus'' care for outcasts and the universal nature of salvation. It includes the birth narrative, parables, and resurrection.'),
       ('JHN', 'en', 'John focuses on Jesus'' divinity and the call to believe in Him for eternal life.',
        'John', 'c. AD 85–90', 'Life of Jesus', 'Presents deep theological reflection on Jesus'' identity and mission, distinct from the Synoptics.',
        'John presents Jesus as the eternal Word, the Son of God. It contains unique signs and discourses, stressing belief, love, and eternal life through Him.'),
       ('ACT', 'en', 'Acts recounts the early church''s formation and the spread of the Gospel through the apostles.',
        'Luke', 'c. AD 63', 'Early Church', 'Traces the expansion of the Gospel through the work of the Holy Spirit and apostolic mission.',
        'Acts follows the work of the Holy Spirit from Pentecost onward, highlighting the ministries of Peter and Paul, and the spread of the Gospel to the Gentiles.'),
       ('ROM', 'en', 'Romans lays out the doctrine of salvation by grace through faith in Jesus Christ.',
        'Paul', 'c. AD 57', 'Paul''s Third Missionary Journey', 'Written to the church in Rome to explain the righteousness of God and the Gospel.',
        'Romans presents a systematic theology of sin, justification, sanctification, and God''s righteousness. It calls for living out the Gospel in everyday life.'),
       ('FIRST_CORINTHIANS', 'en', '1 Corinthians addresses church issues and calls for unity and love.',
        'Paul', 'c. AD 55', 'Early Church', 'Responds to problems and questions in the Corinthian church.',
        'Paul corrects moral and doctrinal problems in the Corinthian church, emphasizing love, spiritual gifts, and the resurrection of the body.'),
       ('SECOND_CORINTHIANS', 'en', '2 Corinthians defends Paul''s apostleship and encourages faith in suffering.',
        'Paul', 'c. AD 56', 'Early Church', 'Paul expresses personal suffering and defends his ministry authority.',
        'Paul shares his ministry struggles, explains true apostolic character, and calls believers to generosity and reconciliation with God and others.'),
       ('GAL', 'en', 'Galatians emphasizes freedom from the Law through faith in Christ.',
        'Paul', 'c. AD 48–49', 'Early Church', 'Addresses Judaizers and defends the doctrine of justification by faith.',
        'Paul rebukes legalism and reaffirms justification by faith. He calls believers to live by the Spirit and not return to slavery under the Law.'),
       ('EPH', 'en', 'Ephesians speaks of the church as the body of Christ and the mystery of the Gospel.',
        'Paul', 'c. AD 60–62', 'Prison Epistles', 'Written to emphasize the unity and purpose of the Church in Christ.',
        'Ephesians explains spiritual blessings in Christ, unity in the church, and how believers should live in light of their calling.'),
       ('PHP', 'en', 'Philippians is a joyful letter encouraging believers to live like Christ.',
        'Paul', 'c. AD 61', 'Prison Epistles', 'Written from prison to thank and encourage the believers in Philippi.',
        'Written from prison, Philippians emphasizes joy, humility, contentment, and perseverance. Christ''s example in chapter 2 is central.'),
       ('COL', 'en', 'Colossians teaches the supremacy of Christ and warns against false teachings.',
        'Paul', 'c. AD 60–62', 'Prison Epistles', 'Written to combat heresies threatening the church at Colossae.',
        'Paul presents Christ as Creator, Sustainer, and Head of the church. He warns against legalism and mysticism, urging growth in Christ alone.'),
       ('FIRST_THESSALONIANS', 'en', '1 Thessalonians encourages steadfastness and hope in the return of Christ.',
        'Paul', 'c. AD 51', 'Early Church', 'Paul praises the believers and offers teaching on Christ''s return.',
        'Paul praises the Thessalonians'' faith and urges holy living. He comforts them with teaching about the resurrection and Christ''s return.'),
       ('SECOND_THESSALONIANS', 'en', '2 Thessalonians clarifies confusion about Christ''s return and urges readiness.',
        'Paul', 'c. AD 51–52', 'Early Church', 'Corrects misunderstandings and warns against laziness.',
        'Paul corrects misunderstandings about the Day of the Lord and warns against idleness, urging believers to stand firm.'),
       ('FIRST_TIMOTHY', 'en', '1 Timothy instructs on church leadership, sound teaching, and godliness.',
        'Paul', 'c. AD 62–64', 'Pastoral Epistles', 'Written to young pastor Timothy with guidelines for church structure and personal conduct.',
        'Paul gives guidelines for church structure, roles of elders and deacons, and the conduct of believers, especially young leaders like Timothy.'),
       ('SECOND_TIMOTHY', 'en', '2 Timothy is Paul''s final letter, urging faithfulness to the Gospel.',
        'Paul', 'c. AD 64–67', 'Pastoral Epistles', 'Written shortly before Paul''s martyrdom to encourage perseverance.',
        'Facing death, Paul encourages Timothy to remain strong in the Word, endure hardship, and pass on the faith boldly and wisely.'),
       ('TIT', 'en', 'Titus provides guidance for church organization and sound doctrine.',
        'Paul', 'c. AD 63–65', 'Pastoral Epistles', 'Instructs Titus on appointing leaders and teaching godly living.',
        'Paul instructs Titus on appointing godly leaders and teaching right living, emphasizing grace as the foundation for godliness.'),
       ('PHM', 'en', 'Philemon appeals for forgiveness and reconciliation of a runaway slave.',
        'Paul', 'c. AD 60–62', 'Prison Epistles', 'A personal letter to Philemon on behalf of Onesimus.',
        'A personal letter urging Philemon to receive Onesimus back as a brother in Christ, modeling love, humility, and reconciliation.'),
       ('HEB', 'en', 'Hebrews presents Christ as the superior high priest and fulfillment of the Old Covenant.',
        'Unknown (possibly Paul or Apollos)', 'c. AD 60–70', 'Jewish-Christian Context',
        'Demonstrates the superiority of Christ over the Old Covenant.',
        'Hebrews exalts Jesus above angels, Moses, and Levitical priests. It encourages perseverance, faith, and appreciation of the New Covenant.'),
       ('JAS', 'en', 'James emphasizes practical faith demonstrated by actions.',
        'James (brother of Jesus)', 'c. AD 45–50', 'Jewish-Christian Context',
        'Encourages believers to live out their faith with integrity and compassion.',
        'James stresses living faith—controlling the tongue, caring for the poor, resisting temptation, and being doers of the Word.'),
       ('FIRST_PETER', 'en', '1 Peter encourages suffering Christians to remain faithful and hopeful.',
        'Peter', 'c. AD 62–64', 'Persecution under Nero', 'Written to scattered believers facing persecution.',
        'Peter offers hope to persecuted believers, urging holiness, submission, and trust in God''s grace amid trials.'),
       ('SECOND_PETER', 'en', '2 Peter warns against false teachers and reminds of Christ''s return.',
        'Peter', 'c. AD 64–68', 'Apostolic Age', 'Encourages spiritual growth and vigilance in the last days.',
        'Peter urges growth in knowledge, warns of heresies, and affirms the certainty of judgment and Christ''s Second Coming.'),
       ('FIRST_JOHN', 'en', '1 John assures believers of eternal life and calls for love and truth.',
        'John', 'c. AD 85–95', 'Early Church', 'Combats early Gnosticism and promotes assurance and love.',
        'John provides tests of true faith: belief in Christ, obedience, and love. He combats early Gnostic heresies.'),
       ('SECOND_JOHN', 'en', '2 John warns against deceivers and urges abiding in Christ''s teachings.',
        'John', 'c. AD 85–95', 'Early Church', 'Short letter encouraging discernment and perseverance in truth.',
        'A short letter urging discernment and avoiding those who deny Christ''s incarnation, while walking in love and truth.'),
       ('THIRD_JOHN', 'en', '3 John commends hospitality and warns against prideful leaders.',
        'John', 'c. AD 85–95', 'Early Church', 'Addresses leadership and support for faithful workers.',
        'John praises Gaius for hospitality, warns against Diotrephes'' arrogance, and encourages support for faithful workers.'),
       ('JUD', 'en', 'Jude urges believers to contend for the faith against ungodly influences.',
        'Jude (brother of James)', 'c. AD 60–80', 'Early Church', 'Warns against corrupt intruders and reminds of apostolic teaching.',
        'Jude warns about false teachers and reminds readers to remain in God''s love, anticipating Christ''s mercy.'),
       ('REV', 'en', 'Revelation reveals end-time visions of judgment, hope, and the ultimate victory of Christ.',
        'John', 'c. AD 95–96', 'Time of Roman Persecution', 'Encourages faithfulness amid trials with visions of Christ''s return.',
        'Revelation presents symbolic visions of judgment, worship, and Christ''s return. It encourages perseverance and proclaims God''s final triumph.');

